### PR TITLE
feat: Add a comment option

### LINKED ISSUE #13: support custom version format
```
new AppCacheWebpackPlugin({
  comments: [
    '[hash][YYYY-MM-DD HH:mm:ss]', // compilation hash, compilation time in moment.js format
    'some other comments'
  ]
})
```

Compilation hash info. is easy to lose, we have to record each release's compilation somewhere, so we need compilation time to known it's which version.
And when I use html-webpack-plugin to generate html file, I just modify the html file template, the compilation hash does not change, maybe it's html-webpack-plugin's duty to update compilation hash, but there are still some edge cases to need additional comments in appcache manifest file.

### PR DESCRIPTION
**Pull request by briandipalma**
closes: #13

### CODE REVIEW

**Comment by briandipalma** [comment]
This allows users to add their own comment to the app cache file. The test shows the version number use case.

**Comment by briandipalma** [comment]
@lettertwo Is this PR OK or are there changes you want made?

**Comment by trueadm** [comment]
@lettertwo any update on this PR?

**Comment by Klathmon** [comment]
I also want to add my request to have this merged. We would really like to add a comment with a version number to our final app cache files just in case we need to know.

**Comment by NekR** [comment]
Just to make sure guys, have you seen this plugin? https://github.com/NekR/offline-plugin

**Comment by Klathmon** [comment]
@NekR I have, however that plugin is significantly more complicated and it requires me to make a pretty significant number of changes across my apps to support both SW and appcache.

This plugin works great, has great and consistant browser support across everything.

**Comment by NekR** [comment]
@Klathmon you do not have to configure everything, you just add `new OfflinePlugin()` without options and it works for most apps exactly as this plugin does. If you need to configure `offline-plugin`, then you need to configure this plugin as well. 

Actually, you do not have to use SW if you do not want:

``` js
new OfflinePlugin({
  ServiceWorker: false
})
```

This will behave same as this plugin and generate only AppCache for your project. 

What is your exact concerns here? Why you have to modify your projects to support plugin? This isn't how it should work and I will be happy to figure out why it doesn't work for you.

**Comment by NekR** [comment]
Any suggestions to simplifying API are welcome too, let's make together it better so all will be able to benefit from SW 👍

**Comment by NekR** [comment]
Just released `v3` version of `offline-plugin`. Tried to simplify README whenever possible, migrated some info to docs/examples (which are not done yet though).

**Comment by lettertwo** [comment]
Sorry for the ridiculously long delay–Merged and published in [1.3.0](https://github.com/lettertwo/appcache-webpack-plugin/tree/v1.3.0).

**Comment by briandipalma** [comment]
Excellent, thanks!

**Pull request merged**
